### ISSUE TITLE
How to use mock? mock数据怎么使用

### ISSUE THREAD

**Issue by mahy50** [DiamondYuan/eumi#3]
请问怎么使用mock数据？
按照umi的配置方式不能用。

**Comment by DiamondYuan** [comment]
和 umi 配置一模一样。按理来说是没问题的。可以提供一个 demo 么。

**Comment by DiamondYuan** [comment]
https://github.com/boilerplate-fe/umi-electron-boilerplate/blob/master/src/renderer/mock/api.ts

**Comment by DiamondYuan** [comment]
mock 需要放到 renderer 下面
