### ISSUE TITLE
在渲染进程中无法使用electron的模块

### ISSUE THREAD

**Issue by mahy50** [DiamondYuan/eumi#4]
使用中发现在react中无法使用electron模块

目前的解决办法是在main进程中预加载一个js，将electron挂载到window上
然后在react中可以使用window.electron.xxx调用electron方法

参考[umi-electron](https://github.com/williamnie/umi-electron/blob/master/src/renderer/public/renderer.js)

**Comment by DiamondYuan** [comment]
> 使用中发现在react中无法使用electron模块
> 
> 目前的解决办法是在main进程中预加载一个js，将electron挂载到window上
> 然后在react中可以使用window.electron.xxx调用electron方法
> 
> 参考[umi-electron](https://github.com/williamnie/umi-electron/blob/master/src/renderer/public/renderer.js)

https://umijs.org/config#externals

**Comment by DiamondYuan** [comment]
electron 不是浏览器的模块，所以不行。
